//import { Inter } from "next/font/google";
import "./global.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/footer";

//const inter = Inter({ susbsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
